# 에러 처리
* 복구가능한(recoverable) 에러
* 복구불가능한(unrecoverable) 에러
* exception과 같은 에러처리 기능 없음

## 복구불가능한 에러 처리: `panic!` 매크로
* 기본적으로 `panic!` 발생시 *unwinding* 수행
  - 스택을 되짚어가며 데이터를 삭제
  - 이는 해야할 일이 많으므로 즉시 멈춤(abort)도 가능
  - 그러려면 `Cargo.toml`에 다음 추가하여 바이너리 파일 크기를 줄임
  ```
  [profile.release]
  panic = 'abort'
  ```

### `panic!` 추적(backtrace)
* `RUST_BACKTRACE=1` 환경변수 설정
  ```rust
  fn main() {
    let v = vec![1, 2, 3];

    v[99];
  }
  ```
  ```
  $ RUST_BACKTRACE=1 cargo run
  ```

## 복구가능한 에러 처리: `Result`
* `Result` 열거형은 `Ok`와 `Err` 두 개의 값을 가짐
  ```rust
  enum Result<T, E> {
    Ok(T),      // 성공하는 경우 데이터형 T
    Err(E),     // 에러의 경우 데이터형 E
  }
  ```
* 예) 파일 열기를 시도했을 때 해당 파일이 없는 경우
  ```rust
  use std::fs::File;

  fn main() {
    let f = File::open("hello.txt");
    // `File::open()`의 반환값은 `Result<T, E>`
    // 성공하는 경우, `T`에 해당하는 파일 핸들러를 담고 있는 `Ok`
    // 실패하는 경우, `E`에 해당하여 에러 정보를 담고 있는 `std::io::Error`

    let f = match f {
      Ok(file) => file,
      Err(error) => {
        panic!("파일 여는데 문제 발생: {:?}", error)
      },
    };
  }
  ```
### 서로 다른 에러에 대한 대응
  ```rust
  use std::fs::File;
  use std::io::ErrorKind;

  fn main() {
    let f = File::open("hello.txt");

    let f = match f {
      Ok(file) => file,
      Err(ref error) if error.kind() == ErrorKind::NotFound => {  // 파일이 없는 경우
                                                                  // ref error와 if match guard 주목
        match File::create("hello.txt") {   // 파일 생성
          Ok(fc) => fc,
          Err(e) => {   // 파일생성하는데 문제가 발생하면
            panic!("Tried to create file but there was a problem: {:?}", e)
          },
        }
      },
      Err(error) => {     // 파일이 없는 경우 외 다른 에러
        panic!("There was a problem opening the file: {:?}", error)
      },
    };
  }
  ```
### `Result<T,E>`가 제공하는 **`unwrap()`과 `expect()`** 메소드
  - `File::open("hello.txt").unwrap()`
    - `Ok`이면 그 안의 `T`값 반환하고 `Err`이면 `panic!` 호출
  - `File::open("hello.txt").expect("Failed to open hello.txt")`
    - `unwrap()`과 마찬가지로 `Ok`이면 그 안의 `T`값 반환하고 `Err`이면 `panic!`호출하되 패닉 기본 메시지 외 지정된 파라미터 표출

### 에러 전파
* 에러 발생한 지점이 아니라 호출한 쪽으로 에러처리 전파
```rust
use std::io;
use std::io::Read;
use std::fs::File;

fn read_username_from_file() -> Result<String, io::Error> {   // 성공하면 String 반환
  let f = File::open("hello.txt");

  let mut f = match f {
    Ok(file) => file,
    Err(e) => return Err(e),    // panic!() 대신 Err(e) 반환
  };

  // 파일 open 성공하면 아래 계속
  let mut s = String::new();

  match f.read_to_string(&mut s) {    // 파일 내용 읽기
    Ok(_) => Ok(s),
    Err(e) => Err(e),
  }
}
```

### 빠른 에러 전파
```rust
use std::io;
use std::io::Read;
use std::fs::File;

fn read_username_from_file() -> Result<String, io::Error> {
    let mut f = File::open("hello.txt")?; // 앞의 예와 같은 기능을 ? 하나로 처리
    let mut s = String::new();
    f.read_to_string(&mut s)?;            // 앞의 예와 같은 기능을 ? 하나로 처리
    Ok(s)
}
```
  - `?`는 표준 라이브러리 내의 `From` trait에 정의된 `from` 함수 호출
  - `from`함수는 어떤 타입의 에러를 다른 타입으로 변환시켜줌
  - `?`는 `Result`를 반환하는 함수 내에서만 사용 가능
```rust
// 더 간단하게
use std::io;
use std::io::Read;
use std::fs::File;

fn read_username_from_file() -> Result<String, io::Error> {
  let mut s = String::new();

  File::open("hello.txt")?.read_to_string(&mut s)?; // 한줄로 표현
  Ok(s)
}
```

## `panic!`과 `Result`의 선택
